// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package config

import (
	"errors"
	"fmt"
	"strings"
)

const (
	// EnvironmentLocal is a Environment of type local.
	EnvironmentLocal Environment = "local"
	// EnvironmentDev is a Environment of type dev.
	EnvironmentDev Environment = "dev"
	// EnvironmentStaging is a Environment of type staging.
	EnvironmentStaging Environment = "staging"
	// EnvironmentProduction is a Environment of type production.
	EnvironmentProduction Environment = "production"
)

var ErrInvalidEnvironment = errors.New("not a valid Environment")

// String implements the Stringer interface.
func (x Environment) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Environment) IsValid() bool {
	_, err := ParseEnvironment(string(x))
	return err == nil
}

var _EnvironmentValue = map[string]Environment{
	"local":      EnvironmentLocal,
	"dev":        EnvironmentDev,
	"staging":    EnvironmentStaging,
	"production": EnvironmentProduction,
}

// ParseEnvironment attempts to convert a string to a Environment.
func ParseEnvironment(name string) (Environment, error) {
	if x, ok := _EnvironmentValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _EnvironmentValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return Environment(""), fmt.Errorf("%s is %w", name, ErrInvalidEnvironment)
}
