// Code generated by MockGen. DO NOT EDIT.
// Source: memdb.go
//
// Generated by this command:
//
//	mockgen -source memdb.go -destination=mock/memdb.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	entity "coupon/internal/app/coupon/entity"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// Mockrepository is a mock of repository interface.
type Mockrepository struct {
	ctrl     *gomock.Controller
	recorder *MockrepositoryMockRecorder
	isgomock struct{}
}

// MockrepositoryMockRecorder is the mock recorder for Mockrepository.
type MockrepositoryMockRecorder struct {
	mock *Mockrepository
}

// NewMockrepository creates a new mock instance.
func NewMockrepository(ctrl *gomock.Controller) *Mockrepository {
	mock := &Mockrepository{ctrl: ctrl}
	mock.recorder = &MockrepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockrepository) EXPECT() *MockrepositoryMockRecorder {
	return m.recorder
}

// FindCouponByCode mocks base method.
func (m *Mockrepository) FindCouponByCode(code string) (entity.Coupon, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindCouponByCode", code)
	ret0, _ := ret[0].(entity.Coupon)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindCouponByCode indicates an expected call of FindCouponByCode.
func (mr *MockrepositoryMockRecorder) FindCouponByCode(code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindCouponByCode", reflect.TypeOf((*Mockrepository)(nil).FindCouponByCode), code)
}

// FindCouponByCodes mocks base method.
func (m *Mockrepository) FindCouponByCodes(codes []string) ([]entity.Coupon, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindCouponByCodes", codes)
	ret0, _ := ret[0].([]entity.Coupon)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindCouponByCodes indicates an expected call of FindCouponByCodes.
func (mr *MockrepositoryMockRecorder) FindCouponByCodes(codes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindCouponByCodes", reflect.TypeOf((*Mockrepository)(nil).FindCouponByCodes), codes)
}

// SaveCoupon mocks base method.
func (m *Mockrepository) SaveCoupon(coupon entity.Coupon) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveCoupon", coupon)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveCoupon indicates an expected call of SaveCoupon.
func (mr *MockrepositoryMockRecorder) SaveCoupon(coupon any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveCoupon", reflect.TypeOf((*Mockrepository)(nil).SaveCoupon), coupon)
}

// Mockcache is a mock of cache interface.
type Mockcache struct {
	ctrl     *gomock.Controller
	recorder *MockcacheMockRecorder
	isgomock struct{}
}

// MockcacheMockRecorder is the mock recorder for Mockcache.
type MockcacheMockRecorder struct {
	mock *Mockcache
}

// NewMockcache creates a new mock instance.
func NewMockcache(ctrl *gomock.Controller) *Mockcache {
	mock := &Mockcache{ctrl: ctrl}
	mock.recorder = &MockcacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockcache) EXPECT() *MockcacheMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *Mockcache) Get(key string) (entity.Coupon, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", key)
	ret0, _ := ret[0].(entity.Coupon)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockcacheMockRecorder) Get(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*Mockcache)(nil).Get), key)
}

// GetList mocks base method.
func (m *Mockcache) GetList(keys []string) []entity.Coupon {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetList", keys)
	ret0, _ := ret[0].([]entity.Coupon)
	return ret0
}

// GetList indicates an expected call of GetList.
func (mr *MockcacheMockRecorder) GetList(keys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetList", reflect.TypeOf((*Mockcache)(nil).GetList), keys)
}

// Save mocks base method.
func (m *Mockcache) Save(key string, data entity.Coupon) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Save", key, data)
}

// Save indicates an expected call of Save.
func (mr *MockcacheMockRecorder) Save(key, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*Mockcache)(nil).Save), key, data)
}
